apiVersion: apps/v1 
kind: Deployment
metadata:
  name: pingtest
  labels:
    app: pinger
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pinger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - image: alpine:3.14
        name: alpine-ctr
        command:
          - /bin/bash
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always